_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.8.0
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 1
                - 16
                - 17
                - 23
                - 55
            "4": 3.8.0
            "5": 0.18.1
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
backbone_model:
    value: vgg
csv_path:
    value: /mnt/hdd/octc/experiment/all.csv
data_dir:
    value: /mnt/hdd/octc/experiment/dataset
epochs:
    value: 200
fold_num:
    value: 1
lr:
    value: 0.0001
save_dir:
    value: /mnt/hdd/octc/experiment/checkpoint
train_augment_list:
    value:
        - RandomHorizontalFlip(p=0.5)
        - RandomVerticalFlip(p=0.5)
        - RandomRotation(degrees=[-45.0, 45.0], interpolation=nearest, expand=False, fill=0)
        - ColorJitter(brightness=(0.8, 1.2), contrast=(0.8, 1.2), saturation=(0.8, 1.2), hue=(-0.2, 0.2))
        - RandomResizedCrop(size=(224, 224), scale=(0.08, 1.0), ratio=(0.75, 1.3333), interpolation=bilinear, antialias=True)
        - Grayscale(num_output_channels=3)
        - ToTensor()
train_batch_size:
    value: 32
valid_augment_list:
    value:
        - Resize(size=(224, 224), interpolation=bilinear, max_size=None, antialias=True)
        - Grayscale(num_output_channels=3)
        - ToTensor()
valid_batch_size:
    value: 8
wandb_project:
    value: multi-pcos-classifier
wandb_use:
    value: true
